/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiaUniversidad.java
 *
 * Created on 18-nov-2011, 23:22:46
 */
package interfaz;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import logica.Datosbd;
import logica.Universidad;

/**
 *
 * @author edward
 */
public class DiaUniversidad extends javax.swing.JDialog {
    private Datosbd bd;
    /** Creates new form DiaUniversidad */
    public DiaUniversidad(java.awt.Frame parent, boolean modal, Datosbd x) {
        super(parent, modal);
        initComponents();
        this.setTitle( App.NAME);
        bd = x;
        cargarDepartamentos();
    }
    
    public boolean verificar(){
        boolean correcto = false;
        if( !txtNombre.getText().isEmpty() &&
            !txtSiglas.getText().isEmpty() )
        {
            correcto = true;
        }
        return correcto;
    }
    
    public void cargarDepartamentos(){
        String[] depas = new String[25];
        depas[0] = "Ancash";
        depas[1] = "Apurímac";
        depas[2] = "Arequima";
        depas[3] = "Ayacucho";
        depas[4] = "Cajamarca";
        depas[5] = "Callao";
        depas[6] = "Cuzco";
        depas[7] = "Amazonas";
        depas[8] = "Ica";
        depas[9] = "Lambayeque";
        depas[10] = "Lima";
        depas[11] = "Huancavelica";
        depas[12] = "Huánuco";
        depas[13] = "Junín";
        depas[14] = "Libertad";
        depas[15] = "Loreto";
        depas[16] = "Madre de Dios";
        depas[17] = "Moquegua";
        depas[18] = "Pasco";
        depas[19] = "Piura";
        depas[20] = "Puno";
        depas[21] = "San Martín";
        depas[22] = "Tacna";
        depas[23] = "Tumbes";
        depas[24] = "Ucayali";
        
        Arrays.sort(depas);
        cmbDepartamentos.removeAllItems();
        for(int i = 0; i < 25; i++){
            cmbDepartamentos.addItem( depas[i] );
        }
    }
    
    private void guardar(){
        Universidad u = new Universidad();
        u.setNombre( txtNombre.getText() );
        u.setSigla( txtSiglas.getText() );
        u.setRegion( cmbDepartamentos.getSelectedItem().toString() );
        try {
            bd.addUniversidad(u);
            this.dispose();
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),
                       App.NAME , JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(),
                       App.NAME , JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSiglas = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmbDepartamentos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Siglas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Región:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtSiglas.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel1.add(txtSiglas, gridBagConstraints);

        txtNombre.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel1.add(txtNombre, gridBagConstraints);

        cmdGuardar.setFont(new java.awt.Font("Tahoma", 1, 18));
        cmdGuardar.setText("Guardar");
        cmdGuardar.setPreferredSize(new java.awt.Dimension(200, 50));
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(cmdGuardar, gridBagConstraints);

        cmbDepartamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDepartamentos.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel1.add(cmbDepartamentos, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-313)/2, (screenSize.height-259)/2, 313, 259);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if( verificar() )
            this.guardar();
    }//GEN-LAST:event_cmdGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDepartamentos;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSiglas;
    // End of variables declaration//GEN-END:variables
}
