/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 18-nov-2011, 11:56:18
 */
package interfaz;

import logica.Datosbd;

/**
 *
 * @author edward
 */
public class MainFrame extends javax.swing.JFrame {
    private Datosbd bd;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setTitle( App.NAME + ": " + App.VERSION);
        bd = new Datosbd();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cmdInscribir = new javax.swing.JButton();
        cmdAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cmdInscribir.setText("Inscribir al evento");
        cmdInscribir.setPreferredSize(new java.awt.Dimension(200, 50));
        getContentPane().add(cmdInscribir, new java.awt.GridBagConstraints());

        cmdAsistencia.setText("Registrar Asistencia");
        cmdAsistencia.setPreferredSize(new java.awt.Dimension(200, 50));
        cmdAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsistenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(cmdAsistencia, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsistenciaActionPerformed
        DiaAsistencia frm = new DiaAsistencia(this, bd);
        frm.setModal(true);
        frm.setVisible(true);
    }//GEN-LAST:event_cmdAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAsistencia;
    private javax.swing.JButton cmdInscribir;
    // End of variables declaration//GEN-END:variables
}
