/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 18-nov-2011, 11:56:18
 */
package interfaz;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import logica.Datosbd;
import logica.Evento;

/**
 *
 * @author edward
 */
public class MainFrame extends javax.swing.JFrame {
    private Datosbd bd;
    private List<Evento> eventos;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setTitle( App.NAME + ": " + App.VERSION);
        bd = new Datosbd();
        eventos = new ArrayList();
        this.cargarEventos();
        this.lblCreditos.setText("Desarrollado por: " + 
                App.DEVELOPERS + 
                "... No fue desarrollador por Pilme Gates");
    }
    
    private void cargarEventos(){
        try {
            eventos = bd.allEventos();
            this.cmbEventos.removeAllItems();
            for( Object obj : eventos){
                cmbEventos.addItem(obj);
            }
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            //Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        cmdInscribir = new javax.swing.JButton();
        cmdAsistencia = new javax.swing.JButton();
        cmbEventos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cmdInscribir.setFont(new java.awt.Font("Tahoma", 0, 18));
        cmdInscribir.setText("Inscribir al evento");
        cmdInscribir.setPreferredSize(new java.awt.Dimension(250, 50));
        cmdInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInscribirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmdInscribir, gridBagConstraints);

        cmdAsistencia.setFont(new java.awt.Font("Tahoma", 0, 18));
        cmdAsistencia.setText("Registrar Asistencia");
        cmdAsistencia.setPreferredSize(new java.awt.Dimension(250, 50));
        cmdAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsistenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmdAsistencia, gridBagConstraints);

        cmbEventos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEventos.setPreferredSize(new java.awt.Dimension(250, 50));
        cmbEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEventosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(cmbEventos, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("EtiCA");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/etica.png"))); // NOI18N
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        lblCreditos.setBackground(new java.awt.Color(51, 204, 0));
        lblCreditos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreditos.setText("No fue desarrollado por Pilmee Gates");
        lblCreditos.setOpaque(true);
        getContentPane().add(lblCreditos, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-634)/2, (screenSize.height-338)/2, 634, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsistenciaActionPerformed
        Evento e = (Evento) cmbEventos.getSelectedItem();
        DiaAsistencia frm = new DiaAsistencia(this, bd,e);
        frm.setModal(true);
        frm.setVisible(true);
    }//GEN-LAST:event_cmdAsistenciaActionPerformed

    private void cmdInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInscribirActionPerformed
       DiaInscripcion frm1 = new DiaInscripcion(this, bd);
       frm1.setModal(true);
       frm1.setVisible(true);
    }//GEN-LAST:event_cmdInscribirActionPerformed

    private void cmbEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try{
                UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
                }catch (Exception ex){}
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEventos;
    private javax.swing.JButton cmdAsistencia;
    private javax.swing.JButton cmdInscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreditos;
    // End of variables declaration//GEN-END:variables
}
